project_id = "qborzwbacpeoznfbjdni"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.firecrawl-map]
verify_jwt = true

[functions.firecrawl-crawl-nav]
verify_jwt = true

[functions.send-password-reset]
verify_jwt = false

[functions.admin-list-users]
verify_jwt = false

[functions.admin-manage-user]
verify_jwt = false

[functions.submit-ticket]
verify_jwt = false

[functions.admin-list-tickets]
verify_jwt = false

[functions.admin-update-ticket]
verify_jwt = false

[functions.submit-contact]
verify_jwt = false

[functions.cancel-team-invite]
verify_jwt = false

[functions.create-lifetime-checkout]
verify_jwt = false

[functions.verify-lifetime-purchase]
verify_jwt = false

[functions.check-url-status]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

